### ISSUE TITLE
Can‘t find the file book_classification.tsv

### ISSUE THREAD

**Issue by Joanna0123** [Babelscape/echoes-from-alexandria#2]
Hello, when I was running the script generate_echoes.py, the error raised that it can't find book_classification.tsv and I can't find it in this repo either. Would you please give me a clue where can I get it?

**Comment by alescire94** [comment]
Dear @Joanna0123, you can find it in the .zip archive uploaded here:
[https://drive.google.com/drive/folders/1Ve5EhafQO2C1RAMiJkpJ7h2PhvlVJrWq?usp=sharing
](https://drive.google.com/drive/folders/1Ve5EhafQO2C1RAMiJkpJ7h2PhvlVJrWq?usp=sharing
)
as indicated in README.md, please download and decompress the . zip archive, then put its content inside 'data'.

Thanks,
Alessandro
